### ISSUE TITLE
PHP7 Support

### ISSUE THREAD

**Issue by gu3st** [tony2001/php-libevent#3]
Hi

I'm wondering when this extension will be updated for PHP 7 and the new changes to it.

Thanks!

**Comment by majuca** [comment]
Me too...

**Comment by ichiriac** [comment]
FYI i'm actually trying to do so : https://github.com/expressif/pecl-event-libevent

**Comment by marcj** [comment]
@ichiriac does it work yet? :)

**Comment by toverux** [comment]
@marcj, just tried, it compiles and loads without error or warning, but I get random errors everywhere in use.

**Comment by ichiriac** [comment]
@marcj it's fixed and works with all my tests

@toverux the main problem with this lib is that there is no unit tests, i've just started to implement them with this release. Any resolved memory leak makes it more stable - give it a new try and if you find problems fill an issue

**Comment by toverux** [comment]
@ichiriac Great :) But now I use php-uv by bwoebi (since libuv seems preferred [in Icicle](https://github.com/icicleio/icicle/blob/master/src/Loop/functions.php#L42) and [in amp](https://github.com/amphp/amp/blob/master/lib/functions.php#L27), plus, it has a lot of features). When I have to use React again, I will try again your port. Good luck!

**Comment by ichiriac** [comment]
@toverux libuv looks really great, I've migrated libevent for historic reasons (old legacy code)

I'm looking for benchmarks to compare perfs of libuv vs libevent
(BTW lcicle uses libev which is more light than libevent but was abandoned by nodejs in favor of libuv)

Another thread pointing in the same direction : https://github.com/facebook/hhvm/issues/2047 (libevent seems a little old/dead)

**Comment by jilieryuyi** [comment]
I try this :https://github.com/expressif/pecl-event-libevent , and get Segmentation fault: 11 error

**Comment by jilieryuyi** [comment]
run with this demo : 
$base = event_base_new();
$event = event_new();

event_set($event, 0, EV_TIMEOUT, function() {
    echo "function called";
});
event_base_set($event, $base);

event_add($event, 5000000);
event_base_loop($base);
